jobs:
  include:
    - before_install:
        - cd create-repository
    - before_install:
        - cd commonjs-babel-plugin
deploy:
  api_key: $NPM_TOKEN
  email: grahamdyson@hotmail.com
  provider: npm
  skip_cleanup: true
install:
  - npm install
  - (cd ../tests; npm install)
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - npm run lint
  - npm test